version: '3.3'
services:
  website:
          image: php:apache
          depends_on:
                  - API
          ports:
                  - 8080:8080
                  - 443:443
          environment:
                  - USERNAME=toto
                  - PASSWORD=python
          volumes:
                  - ./website:/var/www/html

  API:
          image: local_simple_api
          ports:
                  - 5000:5000
          expose:
                  - 5000
          volumes:
                  - ./simple_api/student_age.json:/data/student_age.json
